md out
cd out
..\x64\Release\raytracer1 ..\examples\example1.xml
..\x64\Release\raytracer1 ..\examples\example2.xml
..\x64\Release\raytracer1 ..\examples\example3.xml
..\x64\Release\raytracer1 ..\examples\example4.xml
..\x64\Release\raytracer1 ..\examples\example5.xml
..\x64\Release\raytracer1 ..\examples\example6.xml
..\x64\Release\raytracer1 ..\examples\example7.xml
..\x64\Release\raytracer1 ..\examples\example8.xml
..\x64\Release\raytracer1 ..\examples\example9_lowres.xml
cd ..
